"use client";
import { useMemo, useState } from "react";
import type { ColumnDef, SortingState } from "@tanstack/react-table";
import { getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { Group, Paper, SimpleGrid, Stack, Text } from "@mantine/core";
import { CalendarClock, Search, Video } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { PageToolbar, UiDataTable, UiSelect, UiStatusBadge, UiTextInput } from "@/components/ui";

type Row={child:string; className:string; title:string; time:string; attendance:string; recording:string; status:"Sắp diễn ra"|"Đang live"|"Đã kết thúc"};
const rows:Row[]=[{child:"Nguyễn Minh Anh",className:"IF-2609",title:"Unit 5 · Listening clinic",time:"Hôm nay 18:00-19:30",attendance:"Chưa tham dự",recording:"-",status:"Sắp diễn ra"},{child:"Trần Gia Huy",className:"TOEIC-2609",title:"Mini test review",time:"Hôm qua 19:45",attendance:"Có tham dự",recording:"Sẵn sàng",status:"Đã kết thúc"}];
const role={"Sắp diễn ra":"info","Đang live":"success","Đã kết thúc":"neutral"} as const;
export function ParentOnlineWorkspace(){const[query,setQuery]=useState("");const[status,setStatus]=useState<string|null>("all");const[sorting,setSorting]=useState<SortingState>([]);const data=useMemo(()=>rows.filter(x=>(status==="all"||!status||x.status===status)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[query,status]);const columns=useMemo<ColumnDef<Row>[]>(()=>[{accessorKey:"child",header:"Học viên",cell:({row})=><div><Text fw={600}>{row.original.child}</Text><Text size="xs" c="dimmed">{row.original.className} · {row.original.title}</Text></div>},{accessorKey:"time",header:"Thời gian",cell:({getValue})=><Group gap="xs"><CalendarClock size={15}/><Text size="sm">{getValue<string>()}</Text></Group>},{accessorKey:"status",header:"Trạng thái",cell:({getValue})=>{const v=getValue<Row["status"]>();return <UiStatusBadge role={role[v]}>{v}</UiStatusBadge>}},{accessorKey:"attendance",header:"Điểm danh"},{accessorKey:"recording",header:"Bản ghi"}],[]);const table=useReactTable({data,columns,state:{sorting,globalFilter:query},onSortingChange:setSorting,onGlobalFilterChange:setQuery,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel()});return <div className="page"><PageHeader title="Lớp online của con" subtitle="Phụ huynh theo dõi buổi học online, thời gian tham dự và bản ghi khi được giáo viên cho phép."/><PageToolbar className="toolbar"><UiTextInput value={query} onChange={e=>setQuery(e.currentTarget.value)} leftSection={<Search size={16}/>} placeholder="Tìm học viên, lớp, bản ghi..." style={{minWidth:280}}/><UiSelect w={170} value={status} onChange={setStatus} data={[{value:"all",label:"Tất cả"},{value:"Sắp diễn ra",label:"Sắp diễn ra"},{value:"Đang live",label:"Đang live"},{value:"Đã kết thúc",label:"Đã kết thúc"}]}/></PageToolbar><SimpleGrid cols={{base:1,lg:2}} spacing="md"><Stack><UiDataTable table={table} columnCount={columns.length} minWidth={920} emptyTitle="Không tìm thấy buổi học liên quan."/><Text size="xs" c="dimmed">{table.getRowModel().rows.length}/{rows.length} buổi học · TanStack Table chuẩn chung</Text></Stack><Paper className="panel" p="lg" withBorder><Group justify="space-between"><div><Text fw={700}>Gợi ý an toàn</Text><Text size="sm" c="dimmed">Hệ thống chỉ hiển thị bản ghi khi phụ huynh được phép.</Text></div><Video size={22}/></Group><Text size="sm" c="dimmed" mt="md">Nếu con bạn vắng mặt, trạng thái sẽ hiển thị rõ tại cột điểm danh.</Text></Paper></SimpleGrid></div>}
