"use client";
import { useMemo, useState } from "react";
import type { ColumnDef, SortingState } from "@tanstack/react-table";
import { getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { Group, Paper, Stack, Text } from "@mantine/core";
import { CreditCard, Search } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { PageToolbar, UiButton, UiDataTable, UiStatusBadge, UiTextInput } from "@/components/ui";
type Row={number:string;student:string;description:string;amount:string;due:string;status:"Chờ thanh toán"|"Đã thanh toán"|"Quá hạn"};const rows:Row[]=[{number:"INV-2608-001",student:"Nguyễn Minh Anh",description:"Học phí IELTS Foundation · tháng 8",amount:"2.000.000đ",due:"30/08/2026",status:"Chờ thanh toán"},{number:"INV-2607-014",student:"Nguyễn Minh Anh",description:"Phí tài liệu",amount:"350.000đ",due:"15/08/2026",status:"Đã thanh toán"}];const role={"Chờ thanh toán":"warning","Đã thanh toán":"success","Quá hạn":"danger"} as const;export function BillingWorkspace(){const[q,setQ]=useState("");const[s,setS]=useState<SortingState>([]);const data=useMemo(()=>rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[q]);const columns=useMemo<ColumnDef<Row>[]>(()=>[{accessorKey:"number",header:"Hóa đơn",cell:({row})=><div><Text fw={600}>{row.original.number}</Text><Text size="xs" c="dimmed">{row.original.description}</Text></div>},{accessorKey:"student",header:"Học viên"},{accessorKey:"amount",header:"Số tiền"},{accessorKey:"due",header:"Hạn thanh toán"},{accessorKey:"status",header:"Trạng thái",cell:({getValue})=>{const v=getValue<Row["status"]>();return <UiStatusBadge role={role[v]}>{v}</UiStatusBadge>}}],[]);const table=useReactTable({data,columns,state:{sorting:s,globalFilter:q},onSortingChange:setS,onGlobalFilterChange:setQ,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel()});return <div className="page"><PageHeader title="Tài chính" subtitle="Quản lý hóa đơn, công nợ, giao dịch thanh toán và biên nhận." action="Tạo hóa đơn"/><PageToolbar className="toolbar"><UiTextInput value={q} onChange={e=>setQ(e.currentTarget.value)} leftSection={<Search size={16}/>} placeholder="Tìm hóa đơn, học viên..."/></PageToolbar><Group mb="md"><UiStatusBadge role="warning">2 hóa đơn chờ thanh toán</UiStatusBadge><UiStatusBadge role="success">12 giao dịch thành công</UiStatusBadge></Group><Paper className="panel" p="md" withBorder><UiDataTable table={table} columnCount={columns.length} minWidth={900} emptyTitle="Không tìm thấy hóa đơn."/></Paper><Group justify="flex-end" mt="md"><UiButton leftSection={<CreditCard size={16}/>}>Đối soát thanh toán</UiButton></Group></div>}
