"use client";
import { useMemo, useState } from "react";
import type { ColumnDef, SortingState } from "@tanstack/react-table";
import { getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";
import { Group, Paper, SimpleGrid, Stack, Text } from "@mantine/core";
import { CalendarClock, LinkIcon, Search, Video } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { PageToolbar, UiButton, UiDataTable, UiSelect, UiStatusBadge, UiTextInput } from "@/components/ui";

type Row={className:string; title:string; time:string; provider:string; status:"Sắp diễn ra"|"Đang live"|"Đã kết thúc"; attendance:string; recording:string};
const rows:Row[]=[{className:"IF-2609",title:"Unit 5 · Listening clinic",time:"Hôm nay 18:00-19:30",provider:"Zoom",status:"Sắp diễn ra",attendance:"0/18",recording:"Chưa có"},{className:"TOEIC-2609",title:"Mini test review",time:"Hôm qua 19:45-21:15",provider:"Google Meet",status:"Đã kết thúc",attendance:"14/16",recording:"Sẵn sàng"}];
const role={"Sắp diễn ra":"info","Đang live":"success","Đã kết thúc":"neutral"} as const;
export function TeacherOnlineWorkspace(){const[query,setQuery]=useState("");const[status,setStatus]=useState<string|null>("all");const[sorting,setSorting]=useState<SortingState>([]);const data=useMemo(()=>rows.filter(x=>(status==="all"||!status||x.status===status)&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[query,status]);const columns=useMemo<ColumnDef<Row>[]>(()=>[{accessorKey:"className",header:"Lớp",cell:({row})=><div><Text fw={600}>{row.original.className}</Text><Text size="xs" c="dimmed">{row.original.title}</Text></div>},{accessorKey:"time",header:"Thời gian",cell:({getValue})=><Group gap="xs"><CalendarClock size={15}/><Text size="sm">{getValue<string>()}</Text></Group>},{accessorKey:"provider",header:"Nền tảng"},{accessorKey:"status",header:"Trạng thái",cell:({getValue})=>{const v=getValue<Row["status"]>();return <UiStatusBadge role={role[v]}>{v}</UiStatusBadge>}},{accessorKey:"attendance",header:"Điểm danh"},{accessorKey:"recording",header:"Bản ghi"}],[]);const table=useReactTable({data,columns,state:{sorting,globalFilter:query},onSortingChange:setSorting,onGlobalFilterChange:setQuery,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel()});return <div className="page"><PageHeader title="Lớp học online" subtitle="Giảng viên quản lý lịch live, vào phòng học, theo dõi đồng bộ điểm danh và bản ghi."/><PageToolbar className="toolbar"><UiTextInput value={query} onChange={e=>setQuery(e.currentTarget.value)} leftSection={<Search size={16}/>} placeholder="Tìm lớp, buổi học..." style={{minWidth:280}}/><UiSelect w={170} value={status} onChange={setStatus} data={[{value:"all",label:"Tất cả"},{value:"Sắp diễn ra",label:"Sắp diễn ra"},{value:"Đang live",label:"Đang live"},{value:"Đã kết thúc",label:"Đã kết thúc"}]}/></PageToolbar><SimpleGrid cols={{base:1,xl:2}} spacing="md"><Stack><UiDataTable table={table} columnCount={columns.length} minWidth={980} emptyTitle="Không tìm thấy buổi học online."/><Text size="xs" c="dimmed">{table.getRowModel().rows.length}/{rows.length} buổi học · TanStack Table chuẩn chung</Text></Stack><Paper className="panel" p="lg" withBorder><Group justify="space-between"><div><Text fw={700}>Buổi học kế tiếp</Text><Text size="sm" c="dimmed">Unit 5 · Listening clinic · Zoom</Text></div><Video size={22}/></Group><Group mt="md"><UiButton leftSection={<LinkIcon size={16}/>}>Mở phòng host</UiButton><UiButton variant="default">Xem bản ghi</UiButton></Group></Paper></SimpleGrid></div>}
