"use client";
import { Group, Paper, Stack, Text, SimpleGrid } from "@mantine/core";
import { useState } from "react";
import { CalendarClock, ClipboardCheck, FileText, Video } from "lucide-react";
import { getCoreRowModel, useReactTable } from "@tanstack/react-table";
import { UiButton, UiDataTable, UiStatusBadge } from "@/components/ui";

const students = [
  { student: "Nguyễn Minh Anh", attendance: "12/14", progress: "68%", score: "8.5/10", homework: "Trễ 1 bài" },
  { student: "Trần Gia Huy", attendance: "14/14", progress: "54%", score: "7.2/10", homework: "Đủ bài" },
  { student: "Lê Phương Linh", attendance: "13/14", progress: "76%", score: "9.0/10", homework: "Đủ bài" },
];
function Kpis({ items }: { items: Array<[string, string, "success" | "info" | "warning"]> }) { return <SimpleGrid cols={{ base: 1, xs: 2, md: 4 }}>{items.map(([value, label, role]) => <Paper className={`classInfoCard classInfoCard--${role}`} p="md" key={label}><Text className="classInfoLabel">{label}</Text><Text className="classInfoValue" fw={700} fz="xl">{value}</Text><UiStatusBadge role={role}>Cập nhật</UiStatusBadge></Paper>)}</SimpleGrid>; }
const table = (data: any[], columns: any[], empty: string) => <UiDataTable table={useReactTable({ data, columns, getCoreRowModel: getCoreRowModel() })} columnCount={columns.length} minWidth={760} emptyTitle={empty} />;
export function DetailTabContent({ activeKey }: { activeKey: string }) {
  if (activeKey === "students") return <Stack><Kpis items={[["18", "Học viên", "success"], ["14/18", "Đã tham dự", "info"], ["2", "Cần hỗ trợ", "warning"]]} />{table(students, [{ accessorKey: "student", header: "Học viên" }, { accessorKey: "attendance", header: "Điểm danh" }, { accessorKey: "progress", header: "Tiến độ" }, { accessorKey: "score", header: "Điểm gần nhất" }, { accessorKey: "homework", header: "Bài tập" }], "Chưa có học viên.")}</Stack>;
  if (activeKey === "sessions") return <SessionsTab />;
  if (activeKey === "assignments") return <Stack><Kpis items={[["14", "Chờ chấm trên lớp", "warning"], ["12", "Bài về nhà đã nộp", "info"], ["1", "Bài kiểm tra sắp mở", "success"]]} />{table([{title:"Listening warm-up",type:"Bài tập trên lớp",due:"Trong buổi",submitted:"16/18",graded:"14/18"},{title:"Writing Task 1",type:"Bài tập về nhà",due:"26/08",submitted:"12/18",graded:"0/12"},{title:"Mini test Unit 5",type:"Bài kiểm tra",due:"28/08",submitted:"0/18",graded:"-"}], [{accessorKey:"title",header:"Bài"},{accessorKey:"type",header:"Loại"},{accessorKey:"due",header:"Hạn"},{accessorKey:"submitted",header:"Đã nộp"},{accessorKey:"graded",header:"Đã chấm"}], "Chưa có bài tập.")}</Stack>;
  if (activeKey === "materials") return <Stack><Kpis items={[["5", "Học liệu buổi kế tiếp", "info"], ["4", "Đã công bố", "success"], ["1", "Chưa công bố", "warning"]]} />{table([{title:"IELTS Listening · Warm-up",type:"Bài giảng",status:"Đã công bố",viewer:"Mở trong hệ thống"},{title:"Listening vocabulary pack",type:"Tài liệu tham khảo",status:"Đã công bố",viewer:"Mở trong hệ thống"},{title:"Unit 5 worksheet",type:"Bài tập",status:"Chưa công bố",viewer:"-"}], [{accessorKey:"title",header:"Học liệu"},{accessorKey:"type",header:"Loại"},{accessorKey:"status",header:"Trạng thái"},{accessorKey:"viewer",header:"Cách mở"}], "Chưa có học liệu.")}</Stack>;
  if (activeKey === "attendance") return <Stack><Kpis items={[["14/16", "Buổi gần nhất", "info"], ["87,5%", "Tỷ lệ tham dự", "success"], ["2", "Cần xác minh", "warning"]]} />{table(students.map(x=>({student:x.student,rate:x.attendance,latest:x.student === "Trần Gia Huy" ? "Có mặt" : "Cần ghi",note:x.homework === "Trễ 1 bài" ? "Vắng 2 buổi" : ""})), [{accessorKey:"student",header:"Học viên"},{accessorKey:"rate",header:"Tỷ lệ"},{accessorKey:"latest",header:"Buổi gần nhất"},{accessorKey:"note",header:"Ghi chú"}], "Chưa có dữ liệu điểm danh.")}</Stack>;
  if (activeKey === "scores") return <Stack><Kpis items={[["8,2", "Điểm trung bình", "info"], ["14", "Đã chấm trên lớp", "success"], ["12", "Bài về nhà chờ chấm", "warning"]]} />{table(students.map(x=>({student:x.student,inClass:x.score,test:"8.1",homework:x.homework === "Đủ bài" ? "Chờ chấm" : "-"})), [{accessorKey:"student",header:"Học viên"},{accessorKey:"inClass",header:"Trên lớp"},{accessorKey:"test",header:"Kiểm tra"},{accessorKey:"homework",header:"Bài về nhà"}], "Chưa có điểm.")}</Stack>;
  return <Paper className="classInfoCallout" p="lg"><Text fw={700}>Phản hồi buổi học gần nhất</Text><Text size="sm" c="dimmed" mt="xs">Học viên phản hồi về tốc độ nghe và thời lượng thực hành speaking.</Text></Paper>;
}

function SessionsTab() {
  const rows = [{ id: "session-1", session: "Unit 5 · Listening clinic", date: "24/08 · 18:00", materials: "4/5", attendance: "Chưa ghi", worklog: "Chưa xác nhận", status: "Cần chuẩn bị" }, { id: "session-2", session: "Unit 4 · Grammar review", date: "22/08 · 18:00", materials: "5/5", attendance: "14/16", worklog: "Đã xác nhận", status: "Hoàn tất" }];
  const [selectedId, setSelectedId] = useState(rows[0].id);
  const selected = rows.find((row) => row.id === selectedId) ?? rows[0];
  const columns = [{ accessorKey: "session", header: "Buổi học", cell: ({ row }: any) => <button className="tableLinkButton" type="button" onClick={() => setSelectedId(row.original.id)}><Text fw={600}>{row.original.session}</Text><Text size="xs" c="dimmed">Mở chi tiết buổi học</Text></button> }, { accessorKey: "date", header: "Thời gian" }, { accessorKey: "materials", header: "Học liệu" }, { accessorKey: "attendance", header: "Điểm danh" }, { accessorKey: "worklog", header: "Worklog" }, { accessorKey: "status", header: "Trạng thái", cell: ({ getValue }: any) => <UiStatusBadge role={getValue() === "Hoàn tất" ? "success" : "warning"}>{getValue()}</UiStatusBadge> }];
  return <Stack><Kpis items={[["3", "Buổi tuần này", "info"], ["1", "Cần chuẩn bị", "warning"], ["2/3", "Đã xác nhận", "success"]]} />{table(rows, columns, "Chưa có buổi học.")}<Paper className="classInfoCallout" p="lg"><Group justify="space-between"><div><Text fw={700}>{selected.session}</Text><Text size="sm" c="dimmed">{selected.date} · {selected.status}</Text></div><UiStatusBadge role={selected.status === "Hoàn tất" ? "success" : "warning"}>{selected.status}</UiStatusBadge></Group><SimpleGrid cols={{ base: 1, md: 3 }} mt="md"><Paper className="classInfoCard classInfoCard--info" p="md"><Text className="classInfoLabel">Học liệu</Text><Text className="classInfoValue" fw={700}>{selected.materials}</Text><UiButton size="xs" mt="sm" variant="default" leftSection={<FileText size={14}/>}>Chuẩn bị học liệu</UiButton></Paper><Paper className="classInfoCard classInfoCard--warning" p="md"><Text className="classInfoLabel">Điểm danh</Text><Text className="classInfoValue" fw={700}>{selected.attendance}</Text><UiButton size="xs" mt="sm" variant="default" leftSection={<ClipboardCheck size={14}/>}>Mở điểm danh</UiButton></Paper><Paper className="classInfoCard classInfoCard--success" p="md"><Text className="classInfoLabel">Worklog</Text><Text className="classInfoValue" fw={700}>{selected.worklog}</Text><UiButton size="xs" mt="sm" variant="default" leftSection={<CalendarClock size={14}/>}>Cập nhật worklog</UiButton></Paper></SimpleGrid><Group mt="md"><UiButton leftSection={<Video size={16}/>}>Chọn buổi để bắt đầu</UiButton><UiButton variant="default">Xem bài tập buổi này</UiButton></Group></Paper></Stack>;
}
