import { randomUUID } from "node:crypto";
export type BillingActor={userId:string;organizationId:string;canManageBilling?:boolean};
export type InvoiceRecord={id:string;organizationId:string;studentId:string|null;invoiceNumber:string;description:string;subtotal:number;discountAmount:number;totalAmount:number;paidAmount:number;status:"draft"|"issued"|"partially_paid"|"paid"|"overdue"|"cancelled";dueAt:Date};
export type PaymentRecord={id:string;organizationId:string;invoiceId:string;provider:string;providerTransactionId:string|null;idempotencyKey:string;amount:number;status:"pending"|"succeeded"|"failed"|"refunded"|"cancelled";paidAt:Date|null};
export type BillingRepository={findInvoice(input:{organizationId:string;invoiceId:string}):Promise<InvoiceRecord|null>;findPaymentByKey(input:{organizationId:string;key:string}):Promise<PaymentRecord|null>;savePayment(payment:PaymentRecord):Promise<PaymentRecord>;updateInvoice(invoice:InvoiceRecord):Promise<InvoiceRecord>};
export class BillingError extends Error{constructor(public readonly code:"not_found"|"forbidden"|"invalid_amount"|"idempotency_conflict"|"invoice_unavailable"){super(code)}}
export class BillingService{constructor(private readonly repo:BillingRepository,private readonly now=()=>new Date(),private readonly newId=()=>randomUUID()){}
 async createPayment(actor:BillingActor,input:{invoiceId:string;amount:number;provider:string;idempotencyKey:string}){const existing=await this.repo.findPaymentByKey({organizationId:actor.organizationId,key:input.idempotencyKey});if(existing)return existing;const invoice=await this.repo.findInvoice({organizationId:actor.organizationId,invoiceId:input.invoiceId});if(!invoice)throw new BillingError("not_found");if(input.amount<=0||input.amount>invoice.totalAmount-invoice.paidAmount)throw new BillingError("invalid_amount");if(["draft","cancelled","paid"].includes(invoice.status))throw new BillingError("invoice_unavailable");return this.repo.savePayment({id:this.newId(),organizationId:actor.organizationId,invoiceId:invoice.id,provider:input.provider,providerTransactionId:null,idempotencyKey:input.idempotencyKey,amount:input.amount,status:"pending",paidAt:null})}
 async applyPayment(actor:BillingActor,paymentId:string,providerTransactionId:string){const invoice=await this.repo.findInvoice({organizationId:actor.organizationId,invoiceId:paymentId});if(!invoice)throw new BillingError("not_found");return invoice}
 async markPaid(actor:BillingActor,payment:PaymentRecord){const invoice=await this.repo.findInvoice({organizationId:actor.organizationId,invoiceId:payment.invoiceId});if(!invoice)throw new BillingError("not_found");const paid=Math.min(invoice.totalAmount,invoice.paidAmount+payment.amount);return this.repo.updateInvoice({...invoice,paidAmount:paid,status:paid>=invoice.totalAmount?"paid":"partially_paid",updatedAt:this.now()} as InvoiceRecord)} }
