import { index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { organizations, users } from "../../database/schema/identity-access";
import { students } from "../academic-learning/schema";

export const invoiceStatus = pgEnum("invoice_status", ["draft", "issued", "partially_paid", "paid", "overdue", "cancelled"]);
export const paymentStatus = pgEnum("payment_status", ["pending", "succeeded", "failed", "refunded", "cancelled"]);
export const refundStatus = pgEnum("refund_status", ["requested", "approved", "completed", "rejected"]);
export const accountingSyncStatus = pgEnum("accounting_sync_status", ["pending", "synced", "failed"]);

export const invoices = pgTable("billing_invoices", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), studentId: uuid("student_id").references(() => students.id), invoiceNumber: text("invoice_number").notNull(), description: text("description").notNull(), subtotal: integer("subtotal").notNull(), discountAmount: integer("discount_amount").notNull().default(0), totalAmount: integer("total_amount").notNull(), paidAmount: integer("paid_amount").notNull().default(0), currency: text("currency").notNull().default("VND"), status: invoiceStatus("status").notNull().default("draft"), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), createdByUserId: uuid("created_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ numberUnique: uniqueIndex("billing_invoices_org_number_unique").on(t.organizationId, t.invoiceNumber), studentIndex: index("billing_invoices_org_student_status_index").on(t.organizationId, t.studentId, t.status) }));
export const paymentTransactions = pgTable("billing_payment_transactions", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), invoiceId: uuid("invoice_id").notNull().references(() => invoices.id), provider: text("provider").notNull(), providerTransactionId: text("provider_transaction_id"), idempotencyKey: text("idempotency_key").notNull(), amount: integer("amount").notNull(), currency: text("currency").notNull().default("VND"), status: paymentStatus("status").notNull().default("pending"), paidAt: timestamp("paid_at", { withTimezone: true }), rawEvent: jsonb("raw_event"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ keyUnique: uniqueIndex("billing_payment_org_idempotency_unique").on(t.organizationId, t.idempotencyKey), providerUnique: uniqueIndex("billing_payment_provider_tx_unique").on(t.organizationId, t.provider, t.providerTransactionId), invoiceIndex: index("billing_payment_invoice_status_index").on(t.organizationId, t.invoiceId, t.status) }));
export const refunds = pgTable("billing_refunds", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), paymentTransactionId: uuid("payment_transaction_id").notNull().references(() => paymentTransactions.id), amount: integer("amount").notNull(), reason: text("reason").notNull(), status: refundStatus("status").notNull().default("requested"), requestedByUserId: uuid("requested_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ organizationPaymentIndex: index("billing_refunds_org_payment_index").on(t.organizationId, t.paymentTransactionId, t.status) }));
export const accountingSyncs = pgTable("billing_accounting_syncs", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), idempotencyKey: text("idempotency_key").notNull(), payload: jsonb("payload").notNull(), status: accountingSyncStatus("status").notNull().default("pending"), retryCount: integer("retry_count").notNull().default(0), lastError: text("last_error"), syncedAt: timestamp("synced_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ keyUnique: uniqueIndex("billing_accounting_org_key_unique").on(t.organizationId, t.idempotencyKey), entityIndex: index("billing_accounting_entity_status_index").on(t.organizationId, t.entityType, t.entityId, t.status) }));
export type Invoice = typeof invoices.$inferSelect; export type NewInvoice = typeof invoices.$inferInsert; export type PaymentTransaction = typeof paymentTransactions.$inferSelect; export type NewPaymentTransaction = typeof paymentTransactions.$inferInsert; export type Refund = typeof refunds.$inferSelect; export type AccountingSync = typeof accountingSyncs.$inferSelect;
